# Generated by Django 5.2.7 on 2025-11-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='organization_code',
            new_name='organizationCode',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='organization_name',
            new_name='organizationName',
        ),
    ]
