# Generated by Django 5.2.7 on 2025-11-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organization_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
